### ISSUE TITLE
Some more information on giving this a try?

### ISSUE THREAD

**Issue by jamesyoungdigital** [agilebits/crackme#3]
This isn't an issue as such, more of a feature request for the docs.

I git clone'd agilebits/crackme in my MSYS2/mingw64 terminal, after installing go, and ran 'go get -u github.com/agilebits/crackme'.

As far as I can tell, I can run: go crackme/cmd/chcreator/main.go -t crackme/doc/answers-2018-03-30.json

to see if I have any hits with pre-supplied "answers" for testing, but I get no output after half an hour.  Is that supposed to happen, is it really this slow to compute the results?

Can anyone supply clear guidance for complete newbies to this challenge?  Maybe also a sample hashcat command or two?

Thanks!

**Comment by gsocgsoc** [comment]
Hi,

First you need to convert them into a format that hashcat understands (base64), i'll save you the trouble here:

hashes.txt
```
sha256:100000:itFxKrXWMtjE2sB7eS67Fw==:o6i4645znIb2czLRc2SxSc2I8zuxHu2uBmrDZnEewmY=
sha256:100000:AlqIveYEAi0xv8ssEoJupA==:VgwCWIn4iu8P3CK91gD7XYfWwzYks3UQ664SicK98GY=
sha256:100000:c4tGwzx/+YZaLRS9I2XUCA==:QCopk5n6px+GPC/zvHbeiEbB79SuyFNBHnjcLIlReFo=
sha256:100000:ZmZCDobLoq58n2c1jwDSWA==:A3WMD8tTiARsK8lUr+KurbjyrFKW3wDDXdWuqST6MUY=
sha256:100000:ncZh7AnJSN0WcQQ50VfO8g==:QHPF4cvXeQNHsm4ER3lSIM2TNokhmzRG2ilPUJpYPUg=
sha256:100000:yr8zijm0QQDfTTCL31nnfg==:Quo7quGRICl417j5AXliuranqSlqacslslu/vzG9UKg
sha256:100000:wlGXqMsOXas6pxLGLnZu+w==:vSrQabTk414bwIEmmuRZUyo0t5cdTCFORjkQH8SJ8yU=
```

Then you should grab the AgileWords.txt from https://raw.githubusercontent.com/agilebits/crackme/master/doc/AgileWords.txt

Now you need to feed hashcat with random permutations of three from that wordlist.

```python kuk.py | hashcat -D 1,2 -w 1 --force -O -w 1 --opencl-devices 1,2,3 -m 10900 -a 0 -o cracked.txt hashes.txt```

The generator kuk.py is here:
```
#!/usr/bin/python

from itertools import permutations, combinations
import itertools 
import binascii
import random
import hashlib
file = open('AgileWords.txt', 'r')
kuken = file.readlines()
random.shuffle(kuken)
def byte_to_binary(n):
	return ''.join(str((n & (1 << i)) and 1) for i in reversed(range(8))) 
def hex_to_binary(h):
	return ''.join(byte_to_binary(ord(b)) for b in binascii.unhexlify(h))
for fittan in itertools.permutations(kuken, 3):
	hej = " ".join(str(x).rstrip() for x in fittan)
	#if hex_to_binary(hashlib.sha256(hej).hexdigest())[:2] == "11":
		#print hej
```

It shuffles the wordlist everytime it starts, so if your lucky you win.

Happy cracking

**Comment by jamesyoungdigital** [comment]
Thanks!

So generating the format hashcat can use is base64-enc of the salt then the "derived" part in the json file? Should the strings be integers first, before b64 encoding them?

Cheers.

**Comment by gsocgsoc** [comment]
First let's take one of the examples:

```
{
		"id": "3UOKUEBO",
		"hint": "3 words",
		"sample": true,
		"prf": "HMAC-SHA256",
		"rounds": 100000,
		"salt": "e65814e4382759f85550029e723dc7e7",
		"derived": "5f37a3bd08ac1c7d163294a3cb192ed1407b62bbc6a6259fee55f6e53f754273",
		"pwd": "governor washout beak"
}
```
You need to convert both the salt and the derived to base64 from binary.

So run 
`echo -n 'e65814e4382759f85550029e723dc7e7' | xxd -p -r | base64`
result: `5lgU5DgnWfhVUAKecj3H5w==`
`echo -n '5f37a3bd08ac1c7d163294a3cb192ed1407b62bbc6a6259fee55f6e53f754273' | xxd -p -r | base64`
result: `XzejvQisHH0WMpSjyxku0UB7YrvGpiWf7lX25T91QnM=`

hashcat compatible line:
`sha256:100000:5lgU5DgnWfhVUAKecj3H5w==:XzejvQisHH0WMpSjyxku0UB7YrvGpiWf7lX25T91QnM=`

So now you can try to crack it with the known password
`echo "governor washout beak" | hashcat -D 1,2 -w 1 --force -O -w 1 --opencl-devices 1,2,3 -m 10900 -a 0 -o cracked.txt hashes.txt`

**Comment by jamesyoungdigital** [comment]
Thank you!!

**Comment by jthack** [comment]
Hey @gsocgsoc , are you sure your single hash works? If I do:

```
from itertools import permutations, combinations
import itertools 
import random
import hashlib

hej = "governor washout beak"
if bin(int(hashlib.sha256(hej).hexdigest(), 16))[:4] == "0b01":
	print hej
```

Then it doesn't print out anything. Calling:

```
bin(int(hashlib.sha256(hej).hexdigest(), 16))[:4]
```
returns 0b11 but according to the [projects hints file](https://github.com/agilebits/crackme/blob/master/password-day-2018-2bit-hints.json), the first 2 bits should be 0b01.

Any idea why it doesn't work? I'd like to get my cracking to be able to filter out 3/4ths of the possibilities. 

edit: or is it possible that the hint generator is wrong @jpgoldberg?

**Comment by gsocgsoc** [comment]
Yeah that part didn't work, this is how it should look correctly.

```
#!/usr/bin/python

from itertools import permutations, combinations
import itertools 
import binascii
import random
import hashlib
file = open('AgileWords.txt', 'r')
kuken = file.readlines()
random.shuffle(kuken)
def byte_to_binary(n):
	return ''.join(str((n & (1 << i)) and 1) for i in reversed(range(8))) 
def hex_to_binary(h):
	return ''.join(byte_to_binary(ord(b)) for b in binascii.unhexlify(h))
for fittan in itertools.permutations(kuken, 3):
	hej = " ".join(str(x).rstrip() for x in fittan)
	if hex_to_binary(hashlib.sha256(hej).hexdigest())[:2] == "11":
		print hej
```

Skip using the 0b part and it will match up.

**Comment by jthack** [comment]
~~I think byte_to_binary is a core piece of the puzzle. Which library is that in?~~ @gsocgsoc 

Edit: nvm, i figured it out! :+1:

**Comment by gsocgsoc** [comment]
Oops,

```
#!/usr/bin/python

from itertools import permutations, combinations
import itertools 
import binascii
import random
import hashlib
file = open('AgileWords.txt', 'r')
kuken = file.readlines()
random.shuffle(kuken)
def byte_to_binary(n):
	return ''.join(str((n & (1 << i)) and 1) for i in reversed(range(8))) 
def hex_to_binary(h):
	return ''.join(byte_to_binary(ord(b)) for b in binascii.unhexlify(h))
for fittan in itertools.permutations(kuken, 3):
	hej = " ".join(str(x).rstrip() for x in fittan)
	if hex_to_binary(hashlib.sha256(hej).hexdigest())[:2] == "11":
		print hej
```
