### ISSUE TITLE
Hints possibly wrong

### ISSUE THREAD

**Issue by jthack** [agilebits/crackme#4]
After my comment on #3, I wanted to see if the hint generation was working properly. I took the string "governor washout beak" and just hashed it with sha256 unsalted, a single time and got:
7a754baa484373bfeb4d0ec3e71b07ebbbb1e5293486eb964ca90a2e3ec95ef8

I cracked this hash with the string via hashcat to confirm I had hashed it properly. If you convert this from hex to binary, you get: 

`111101001110101010010111010101001001000010000110111001110111111111010110100110100001110110000111110011100011011000001111110101110111011101100011110010100101001001101001000011011101011100101100100110010101001000010100010111000111110110010010101111011111000`

[Based on this commit ](https://github.com/agilebits/crackme/commit/40df6913f35dac1dbf6096a72371d90cb1651844#diff-2b540549119260be1eda946aac87d981), the hint generator thinks the hint should be:
{"governor washout beak", 3, "0b011"}

but 011 is neither the first 3 bits nor the last three bits (I mention this because initially I thought I might have been confused about whether @jpgoldberg was giving the first bits or last bits). I'm no expert, so I may be wrong, but I'm pretty sure that the hints are not correct. 

Thanks, and let me know if I can provide any further information!

**Comment by jthack** [comment]
This comment in your code is correct, but if you take those values (76, 3f, 8b, and 04) and convert them to binary, they don't match the testing baselines. So, it's the go code hint generator that's wrong. 

```
/* For tests I need the first byte of the sha256 hash of some strings

	Using

		for p in one two three four "governor washout beak" "glassy ubiquity absence" "splendor excel rarefy"; do
			h=$(echo -n $p | shasum -a256 | cut -b1-2)
			echo "$p:  $h"
		done

	I got

		one:  76
		two:  3f
		three:  8b
		four:  04
	*/
```

**Comment by jthack** [comment]
@jpgoldberg I've been debugging it and this is the problematic line in MakeBitHint():
`lead >>= 8 - uint(bits)`
If you comment out that line, it outputs the full 8 bits each time, but they're correct.

**Comment by jthack** [comment]
~~If you change that line (129 of crackme.go) to `lead >>= 7 - uint(bits)`, it fixes it. Hope that helps!~~
Working on a fix now. But yeah, the variable lead is correct, you just need to chop the bits off of it correctly.

**Comment by jpgoldberg** [comment]
OK. This is a serious bug. And I can't believe that I didn't construct tests based on my openssl checks.

**Comment by jpgoldberg** [comment]
Oh. I did create tests. And the first three bits of "7a..." are "011".

Your binary representation is striping leading zeros.

**Comment by jthack** [comment]
Interesting. Apparently online converters to binary AND python code `hashlib.sha256(pw).hexdigest()` both strip leading zeros.
